import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';


//https://api.github.com/users/answebdev

export default function About({ repos }) {
    // console.log(repos);

    return (
        <div className={styles.container}>
            <Head>
                <title>Bacon Blog | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>
                    About Page
                </h1>

                <h3>Check out my GitHub repos</h3>

                {repos.map((repo) => {
                    return (
                        <div>
                            {/* <p>{repo.name}: {repo.description}</p> */}
                            <a style={{ color: 'tomato' }} href={repo.svn_url} target='_blank' rel='noopener noreferrer'>
                                {repo.name}
                            </a>
                        </div>
                    );
                })}
                {/* {articles.map((article) => {
                    return (
                        <div>
                            <p>{article.title}</p>
                        </div>
                    );
                })} */}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}



export const getStaticProps = async () => {
    const res = await fetch('https://api.github.com/users/answebdev/repos');
    const repos = await res.json();

    return {
        props: {
            repos,
        },
    };
};

// export const getStaticProps = async () => {
//     const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`);
//     const articles = await res.json();

//     return {
//         props: {
//             articles,
//         },
//     };
// };